In [46]:
import os
import pandas as pd
a=pd.read_csv("/Users/kailong/Desktop/rtEnv/rtSynth_rt/subjects/sub002/adaptiveThreshold.csv")
a

,sub,session,run,threshold,successful_trials,perfect_trials,monetaryReward1,monetaryReward5,monetaryReward9,monetaryReward13
0,sub002,2,1,0.60,12.0,6.0,NaN,NaN,NaN,NaN
1,sub002,2,2,0.60,12.0,8.0,NaN,NaN,NaN,NaN
2,sub002,2,3,0.60,12.0,3.0,NaN,NaN,NaN,NaN
3,sub002,2,4,0.60,10.0,3.0,NaN,NaN,NaN,NaN
4,sub002,2,5,0.60,11.0,8.0,NaN,NaN,NaN,NaN
5,sub002,2,6,0.60,12.0,6.0,NaN,NaN,NaN,NaN
6,sub002,2,7,0.65,8.0,3.0,1080.0,721.0,720.0,1440.0
7,sub002,2,8,0.65,6.0,1.0,360.0,360.0,1081.0,2160.0
8,sub002,2,9,0.65,11.0,3.0,721.0,1080.0,1800.0,360.0
9,sub002,2,10,0.70,10.0,5.0,1799.0,360.0,1440.0,361.0
10,sub002,3,2,0.65,10.0,5.0,5.0,2.0,3.0,3.0
11,sub002,3,3,0.60,11.0,3.0,3.0,5.0,3.0,2.0
12,sub002,3,4,0.65,10.0,3.0,3.0,2.0,5.0,3.0
13,sub002,3,5,0.70,4.0,0.0,0.0,0.0,4.0,9.0
14,sub002,3,6,0.70,6.0,1.0,1.0,0.0,5.0,7.0
15,sub002,3,7,0.70,10.0,4.0,4.0,2.0,4.0,3.0
16,sub002,3,8,0.70,11.0,7.0,7.0,3.0,1.0,2.0
17,sub002,3,9,0.75,9.0,2.0,2.0,3.0,4.0,4.0
18,sub002,3,10,0.80,6.0,0.0,0.0,3.0,3.0,7.0
19,sub002,3,11,0.80,4.0,1.0,1.0,2.0,1.0,9.0
20,sub002,3,12,0.80,10.0,5.0,5.0,1.0,4.0,3.0
21,sub002,3,1,0.80,3.0,0.0,0.0,0.0,3.0,1.0